package com.fridge.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF8C4E29)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFAE2D8)
val onPrimaryContainerLight = Color(0xFF703714)
val secondaryLight = Color(0xFF765848)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFDBCA)
val onSecondaryContainerLight = Color(0xFF5C4132)
val tertiaryLight = Color(0xFF636032)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFEAE5AB)
val onTertiaryContainerLight = Color(0xFF4B481D)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF8F6)
val onBackgroundLight = Color(0xFF221A15)
val surfaceLight = Color(0xFFFFF8F6)
val onSurfaceLight = Color(0xFF221A15)
val surfaceVariantLight = Color(0xFFF4DED4)
val onSurfaceVariantLight = Color(0xFF52443D)
val outlineLight = Color(0xFF85746B)
val outlineVariantLight = Color(0xFFD7C2B9)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF382E29)
val inverseOnSurfaceLight = Color(0xFFFFEDE6)
val inversePrimaryLight = Color(0xFFFFB68F)
val surfaceDimLight = Color(0xFFE8D7CF)
val surfaceBrightLight = Color(0xFFFFF8F6)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF1EB)
val surfaceContainerLight = Color(0xFFFCEAE3)
val surfaceContainerHighLight = Color(0xFFF6E5DD)
val surfaceContainerHighestLight = Color(0xFFF0DFD8)
